\set ON_ERROR_STOP on

-- RUN_ID is generated by scripts/profile-order-admission.sh and contains only
-- timestamp, run number, letters, digits, and hyphens.
WITH run_orders AS (
    SELECT id, reference_id AS order_id
    FROM ledger_journals
    WHERE journal_type = 'trading_funds_reserved'
      AND reference_id LIKE 'distributed-order-' || :'run_id' || '-%'
),
violations AS (
    SELECT 'reservation_count' AS check_name, count(*) AS violation_count
    FROM run_orders j
    LEFT JOIN fund_reservations r ON r.order_id = j.order_id
    WHERE r.id IS NULL

    UNION ALL

    SELECT 'ledger_entry_count', count(*)
    FROM run_orders j
    LEFT JOIN LATERAL (
        SELECT count(*) AS entry_count
        FROM ledger_entries e
        WHERE e.journal_id = j.id
    ) e ON true
    WHERE e.entry_count <> 2

    UNION ALL

    SELECT 'outbox_count', count(*)
    FROM run_orders j
    LEFT JOIN outbox_events o
      ON o.aggregate_id = j.order_id
     AND o.event_type = 'FundsReserved'
    WHERE o.id IS NULL

    UNION ALL

    SELECT 'unbalanced_journal_asset', count(*)
    FROM (
        SELECT e.journal_id, e.asset_id
        FROM ledger_entries e
        JOIN run_orders j ON j.id = e.journal_id
        GROUP BY e.journal_id, e.asset_id
        HAVING sum(e.amount_atomic) FILTER (WHERE e.side = 'debit')
             <> sum(e.amount_atomic) FILTER (WHERE e.side = 'credit')
    ) unbalanced

    UNION ALL

    SELECT 'negative_balance', count(*)
    FROM user_asset_balances
    WHERE available_atomic < 0
       OR reserved_atomic < 0
       OR withdrawal_pending_atomic < 0
       OR deposit_pending_atomic < 0
       OR hold_atomic < 0

    UNION ALL

    SELECT 'duplicate_order', count(*)
    FROM (
        SELECT order_id
        FROM fund_reservations
        WHERE order_id LIKE 'distributed-order-' || :'run_id' || '-%'
        GROUP BY order_id
        HAVING count(*) <> 1
    ) duplicates
)
SELECT check_name, violation_count
FROM violations
ORDER BY check_name;
